// <auto-generated />
namespace Restaurant_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updatedatatbase_after_constrains : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedatatbase_after_constrains));
        
        string IMigrationMetadata.Id
        {
            get { return "202005061806577_updatedatatbase_after_constrains"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
