// <auto-generated />
namespace Restaurant_Management_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialy));
        
        string IMigrationMetadata.Id
        {
            get { return "202006061545225_initialy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
